spring:
  datasource:
    url: jdbc:mysql://localhost:3306/covid-stat?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
      globally_quoted_identifiers: true
    show-sql: true

  server:
    error:
    include-message: always
    include-binding-errors: always

